linters:
  enable:
    - goheader
    - errorlint
    - gocritic
    - godox
    - gofmt
    - gosec
    - misspell
    - nilerr

linters-settings:
  goheader:
    template-path: ".header.txt"
    values:
      const:
        Owner: "Aree Enterprises, Inc. and Contributors"
